export const history = {
  list: [
    {
      history_pk: 1,
      year: 2015,
      month: 9,
      content_kr: '(주) 아이디어콘서트 설립',
      content_id: 'Pendirian Idea Concert Co., Ltd',
      content_pt: 'Criação da IDEACONCERT Co., Ltd',
      content_us: 'Idea Concert Co., Ltd established',
      active_flag: 1,
      regdate: '2020-04-22 09:48:54',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 1
    },
    {
      history_pk: 2,
      year: 2015,
      month: 9,
      content_kr: '6개월 챌린지 지원 사업 선정',
      content_id: 'Terpilih dalam "6-Month Challenge Support Project"',
      content_pt: 'Seleção no Projeto 6 Meses de Suporte a Desafios',
      content_us: 'Selected as a 6-Month Challenge Support Project',
      active_flag: 1,
      regdate: '2020-04-22 09:49:48',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 2
    },
    {
      history_pk: 5,
      year: 2016,
      month: 11,
      content_kr: 'KT 글로벌 상생 프로젝트 선정',
      content_id: 'Terpilih dalam Projek KT Global Win-Win',
      content_pt: 'Seleção no Projeto KT Global Win-Win',
      content_us: 'Selected on KT Global Win-win Project',
      active_flag: 1,
      regdate: '2020-04-22 09:57:23',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 3
    },
    {
      history_pk: 6,
      year: 2016,
      month: 9,
      content_kr: '웹툰 저작 솔루션 문화 기술 사업 선정',
      content_id: 'Terpilih dalam Projek Webtoon Authoring Solution Culture Technology',
      content_pt: 'Seleção como Empresa de Tecnologia Cultural Para Solução de Criação de Webtoons',
      content_us: 'Selected on Webtoon Authoring Solution Culture Technology Project',
      active_flag: 1,
      regdate: '2020-04-22 09:57:52',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 4
    },
    {
      history_pk: 7,
      year: 2016,
      month: 9,
      content_kr: '경기 창조 혁신 센터 보육기업 선정',
      content_id: 'Terpilih sebagai Childcare Company oleh Gyeonggi Creative Innovation Center',
      content_pt: 'Seleção como Empresa de Cuidado Infantil pelo Centro de Inovação Criativa de Gyeonggi',
      content_us: 'Selected as a Childcare Company by Gyeonggi Creative Innovation Center',
      active_flag: 1,
      regdate: '2020-04-22 09:58:39',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 5
    },
    {
      history_pk: 8,
      year: 2016,
      month: 3,
      content_kr: '웹툰 무비 솔루션 프로젝트 기획',
      content_id: 'Merencakan Projek Webtoon Movie Solution',
      content_pt: 'Planejamento do Projeto de Soluções de Webtoon Movies',
      content_us: 'Plan a Webtoon Movie Solution Project',
      active_flag: 1,
      regdate: '2020-04-22 09:59:07',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 6
    },
    {
      history_pk: 9,
      year: 2017,
      month: 12,
      content_kr: 'ICT 유망기업 선정(K-global 300)',
      content_id: 'Terpilih sebagai Perusahaan ICT yang menjanjikan(K-global 300)',
      content_pt: 'Seleção como Companhia Promissora de NTCI(K-global 300)',
      content_us: 'Selected as a Promising ICT Company(K-global 300)',
      active_flag: 1,
      regdate: '2020-04-22 09:59:34',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 7
    },
    {
      history_pk: 10,
      year: 2017,
      month: 9,
      content_kr: 'KT신사업팀과 업무 협약',
      content_id: 'Berhasil melakukan perjanjian bisnis dengan tim KT New Business',
      content_pt: 'Contrato com a Equipe de New Business da KT',
      content_us: 'Business agreement with KT new business team',
      active_flag: 1,
      regdate: '2020-04-22 10:00:10',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 8
    },
    {
      history_pk: 11,
      year: 2017,
      month: 6,
      content_kr: '스마트미디어 지원 사업 선정',
      content_id: 'Terpilih dalam Program Smart Media Support',
      content_pt: 'Seleção no Programa de Apoio Smart Media',
      content_us: 'Selected on Smart Media Support Program',
      active_flag: 1,
      regdate: '2020-04-22 10:01:17',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 9
    },
    {
      history_pk: 12,
      year: 2017,
      month: 4,
      content_kr: '가천대학교 경기 창조 혁신 센터 보육기업 선정',
      content_id: 'Terpilih sebagai Childcare Company oleh Universitas Gachon, Gyeonggi Creative Innovation Center',
      content_pt:
        'Seleção como Empresa de Cuidado Infantil pelo Centro de Inovação Criativa da Universidade de Gachon, Gyeonggi',
      content_us: 'Selected as a Childcare Company by Gachon University Gyeonggi Creative Innovation Center',
      active_flag: -1,
      regdate: '2020-04-22 10:02:10',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 10
    }
  ]
};
