export const history = {
  list: [
    {
      history_pk: 1,
      year: 2015,
      month: 9,
      content_kr: '(주) 아이디어콘서트 설립',
      content_id: 'Pendirian Idea Concert Co., Ltd',
      content_pt: 'Criação da IDEACONCERT Co., Ltd',
      content_us: 'Idea Concert Co., Ltd established',
      active_flag: 1,
      regdate: '2020-04-22 09:48:54',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 1
    },
    {
      history_pk: 2,
      year: 2015,
      month: 9,
      content_kr: '6개월 챌린지 지원 사업 선정',
      content_id: 'Terpilih dalam "6-Month Challenge Support Project"',
      content_pt: 'Seleção no Projeto 6 Meses de Suporte a Desafios',
      content_us: 'Selected as a 6-Month Challenge Support Project',
      active_flag: 1,
      regdate: '2020-04-22 09:49:48',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 2
    },
    {
      history_pk: 5,
      year: 2016,
      month: 11,
      content_kr: 'KT 글로벌 상생 프로젝트 선정',
      content_id: 'Terpilih dalam Projek KT Global Win-Win',
      content_pt: 'Seleção no Projeto KT Global Win-Win',
      content_us: 'Selected on KT Global Win-win Project',
      active_flag: 1,
      regdate: '2020-04-22 09:57:23',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 3
    },
    {
      history_pk: 6,
      year: 2016,
      month: 9,
      content_kr: '웹툰 저작 솔루션 문화 기술 사업 선정',
      content_id: 'Terpilih dalam Projek Webtoon Authoring Solution Culture Technology',
      content_pt: 'Seleção como Empresa de Tecnologia Cultural Para Solução de Criação de Webtoons',
      content_us: 'Selected on Webtoon Authoring Solution Culture Technology Project',
      active_flag: 1,
      regdate: '2020-04-22 09:57:52',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 4
    },
    {
      history_pk: 7,
      year: 2016,
      month: 9,
      content_kr: '경기 창조 혁신 센터 보육기업 선정',
      content_id: 'Terpilih sebagai Childcare Company oleh Gyeonggi Creative Innovation Center',
      content_pt: 'Seleção como Empresa de Cuidado Infantil pelo Centro de Inovação Criativa de Gyeonggi',
      content_us: 'Selected as a Childcare Company by Gyeonggi Creative Innovation Center',
      active_flag: 1,
      regdate: '2020-04-22 09:58:39',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 5
    },
    {
      history_pk: 8,
      year: 2016,
      month: 3,
      content_kr: '웹툰 무비 솔루션 프로젝트 기획',
      content_id: 'Merencakan Projek Webtoon Movie Solution',
      content_pt: 'Planejamento do Projeto de Soluções de Webtoon Movies',
      content_us: 'Plan a Webtoon Movie Solution Project',
      active_flag: 1,
      regdate: '2020-04-22 09:59:07',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 6
    },
    {
      history_pk: 9,
      year: 2017,
      month: 12,
      content_kr: 'ICT 유망기업 선정(K-global 300)',
      content_id: 'Terpilih sebagai Perusahaan ICT yang menjanjikan(K-global 300)',
      content_pt: 'Seleção como Companhia Promissora de NTCI(K-global 300)',
      content_us: 'Selected as a Promising ICT Company(K-global 300)',
      active_flag: 1,
      regdate: '2020-04-22 09:59:34',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 7
    },
    {
      history_pk: 10,
      year: 2017,
      month: 9,
      content_kr: 'KT신사업팀과 업무 협약',
      content_id: 'Berhasil melakukan perjanjian bisnis dengan tim KT New Business',
      content_pt: 'Contrato com a Equipe de New Business da KT',
      content_us: 'Business agreement with KT new business team',
      active_flag: 1,
      regdate: '2020-04-22 10:00:10',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 8
    },
    {
      history_pk: 11,
      year: 2017,
      month: 6,
      content_kr: '스마트미디어 지원 사업 선정',
      content_id: 'Terpilih dalam Program Smart Media Support',
      content_pt: 'Seleção no Programa de Apoio Smart Media',
      content_us: 'Selected on Smart Media Support Program',
      active_flag: 1,
      regdate: '2020-04-22 10:01:17',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 9
    },
    {
      history_pk: 12,
      year: 2017,
      month: 4,
      content_kr: '가천대학교 경기 창조 혁신 센터 보육기업 선정',
      content_id: 'Terpilih sebagai Childcare Company oleh Universitas Gachon, Gyeonggi Creative Innovation Center',
      content_pt:
        'Seleção como Empresa de Cuidado Infantil pelo Centro de Inovação Criativa da Universidade de Gachon, Gyeonggi',
      content_us: 'Selected as a Childcare Company by Gachon University Gyeonggi Creative Innovation Center',
      active_flag: -1,
      regdate: '2020-04-22 10:02:10',
      lastpage: 4,
      nowpage: 1,
      listpage: 10,
      rowcnt: '38',
      rownum: 10
    }
  ]
};
export const location = {
  list: [
    {
      location_pk: 1,
      name_kr: '판교 본사',
      name_id: 'Kantor Pusat Pangyo',
      name_pt: 'Sede em Pangyo',
      name_us: "Pangyo's Head Office",
      post_code: 13449,
      road_address_kr: '경기 성남시 수정구 대왕판교로 815',
      road_address_id: '815 Daewangpangyo-ro, Sujeong-gu, Seongnam-si, Gyeonggi-do, South Korea',
      road_address_pt: '815 Daewangpangyo-ro, Sujeong-gu, Seongnam-si, Gyeonggi-do, South Korea',
      road_address_us: '815 Daewangpangyo-ro, Sujeong-gu, Seongnam-si, Gyeonggi-do, South Korea',
      detail_address_kr: '판교기업지원허브 ICT문화융합센터 430호',
      detail_address_id: '',
      detail_address_pt: '',
      detail_address_us: '',
      contact: '070-8825-5004',
      fax: '031-5182-9048',
      regdate: '2020-04-22 10:37:47',
      check_open: 'Y',
      lastpage: 0,
      nowpage: 1,
      listpage: 10,
      rowcnt: '3',
      rownum: 1
    },
    {
      location_pk: 2,
      name_kr: 'AI연구센터',
      name_id: 'AI Research Center',
      name_pt: 'Centro de Pesquisa IA',
      name_us: 'AI Research Center',
      post_code: 6770,
      road_address_kr: '서울 서초구 매헌로8길 47',
      road_address_id: ' Maeheon-ro 8gil 47, Seocho-gu, Seoul, South Korea',
      road_address_pt: 'Maeheon-ro 8-gil, 47, Seocho-gu, Seul, Coreia do Sul',
      road_address_us: ' Maeheon-ro 8gil 47, Seocho-gu, Seoul, South Korea',
      detail_address_kr: '407호',
      detail_address_id: 'Office No. 407',
      detail_address_pt: 'Sala 407',
      detail_address_us: 'Office No. 407',
      contact: '070-8825-5004',
      fax: '031-5182-9048',
      regdate: '2020-04-22 11:02:20',
      check_open: 'Y',
      lastpage: 0,
      nowpage: 1,
      listpage: 10,
      rowcnt: '3',
      rownum: 2
    },
    {
      location_pk: 3,
      name_kr: '제주 지사 플레이콘',
      name_id: "Kantor Cabang Jeju 'Playcon'",
      name_pt: 'Escritório na Ilha de Jeju',
      name_us: "Jeju Branch Office 'Playcon'",
      post_code: 63208,
      road_address_kr: '제주특별자치도 제주시 중앙로 217',
      road_address_id: '217 Jungang-ro, Jeju-si, Jeju-do, South Korea',
      road_address_pt: '217 Jungang-ro, Jeju-si, Jeju-do, South Korea',
      road_address_us: '217 Jungang-ro, Jeju-si, Jeju-do, South Korea',
      detail_address_kr: '제주벤처마루 701호',
      detail_address_id: 'Jeju Venture Maru room 701',
      detail_address_pt: 'Jeju Venture Maru sala 701',
      detail_address_us: 'Jeju Venture Maru room 701',
      contact: '070-8825-5004',
      fax: '031-5182-9048',
      regdate: '2020-04-22 11:05:57',
      check_open: 'Y',
      lastpage: 0,
      nowpage: 1,
      listpage: 10,
      rowcnt: '3',
      rownum: 3
    }
  ]
};
export const promotion = {
  list: [
    {
      promotion_pk: 2,
      promotion_name: '쿠키런',
      promotion_url: 'https://www.youtube.com/embed/VHo2U9lqV4Y',
      view_status: 'Y',
      regdate: '2021-12-29 15:22:19',
      lastpage: 10,
      nowpage: 1,
      listpage: 10,
      rowcnt: '93',
      rownum: 1
    },
    {
      promotion_pk: 3,
      promotion_name: '웹툰 벨롱벨롱 식탁 홍보영상 ver.2',
      promotion_url: 'https://www.youtube.com/embed/eP8EuWlfQW0',
      view_status: 'Y',
      regdate: '2021-12-29 15:34:05',
      lastpage: 10,
      nowpage: 1,
      listpage: 10,
      rowcnt: '93',
      rownum: 2
    },
    {
      promotion_pk: 4,
      promotion_name: '웹툰 영상을 만드는 가장 손쉬운 방법, 아이디어콘서트',
      promotion_url: 'https://www.youtube.com/embed/X1bV1oB3zaw',
      view_status: 'Y',
      regdate: '2021-12-29 15:44:13',
      lastpage: 10,
      nowpage: 1,
      listpage: 10,
      rowcnt: '93',
      rownum: 3
    },
    {
      promotion_pk: 5,
      promotion_name: '웹툰 벨롱벨롱식탁 홍보영상',
      promotion_url: 'https://www.youtube.com/embed/dX3caTwSeKw',
      view_status: 'Y',
      regdate: '2021-12-29 15:44:54',
      lastpage: 10,
      nowpage: 1,
      listpage: 10,
      rowcnt: '93',
      rownum: 4
    },
    {
      promotion_pk: 6,
      promotion_name: '2021 코툰 마켓',
      promotion_url: 'https://www.youtube.com/embed/mSsUDD1OOek',
      view_status: 'Y',
      regdate: '2021-12-29 15:45:32',
      lastpage: 10,
      nowpage: 1,
      listpage: 10,
      rowcnt: '93',
      rownum: 5
    },
    {
      promotion_pk: 7,
      promotion_name: 'Ideaconcert Official 6Seconds',
      promotion_url: 'https://www.youtube.com/embed/R1XEYkQii6Q',
      view_status: 'Y',
      regdate: '2021-12-29 15:46:12',
      lastpage: 10,
      nowpage: 1,
      listpage: 10,
      rowcnt: '93',
      rownum: 6
    },
    {
      promotion_pk: 8,
      promotion_name:
        'Tear Thief (The Forbidden Marriage X Kim Jong Kook) MV / 웹툰 금혼령 OST 눈물을 훔치다x김종국 MV영상',
      promotion_url: 'https://www.youtube.com/embed/IV6A6BuFNVg',
      view_status: 'Y',
      regdate: '2021-12-29 15:46:33',
      lastpage: 10,
      nowpage: 1,
      listpage: 10,
      rowcnt: '93',
      rownum: 7
    }
  ]
};
